server:
  port: 8080

spring:
  servlet:
    multipart:
      max-request-size: 2GB
      max-file-size: 2GB

  datasource:
    username: genshin_impact
    password: 114514!!
    url: jdbc:mysql://localhost:3306/genshin_impact_info?serverTimezone=Asia/Shanghai&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.erizeez.genshinimpactdamagecalculatorserver.entity

#showSql
logging:
  level:
    com:
      erizeez:
        genshinimpactdamagecalculatorserver:
          repository: debug